
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_BUTTON_DEVICE_ID,
		XPAR_AXI_GPIO_BUTTON_BASEADDR,
		XPAR_AXI_GPIO_BUTTON_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_BUTTON_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_FREQ_DEVICE_ID,
		XPAR_AXI_GPIO_FREQ_BASEADDR,
		XPAR_AXI_GPIO_FREQ_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_FREQ_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_SWITCHES_DEVICE_ID,
		XPAR_AXI_GPIO_SWITCHES_BASEADDR,
		XPAR_AXI_GPIO_SWITCHES_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_SWITCHES_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_VOL_DEVICE_ID,
		XPAR_AXI_GPIO_VOL_BASEADDR,
		XPAR_AXI_GPIO_VOL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_VOL_IS_DUAL
	}
};


